---
- hosts: windows 
  gather_facts: false
  name: "Checks a user is created, and if it is not it will create the following user"
  tasks:
    -
      name: "Checks a user is created, and if it is not it will create the following user"
      win_domain_user:
        firstname: "{{ active_directory_user_firstname }}"
        name: "{{ active_directory_user_name }}"
        password: "{{ active_directory_user_password }}"
        state: present
        surname: "{{ active_directory_user_surname }}"
  vars:
    ansible_connection: winrm
    ansible_password: "{{ ansible_password }}"
    ansible_port: 5985
    ansible_user: "{{ ansible_username }}"
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
