--- 
- 
  gather_facts: false
  hosts: windows  
  # connection: winrm
  name: "Checks a user is created, and if it is not it will create the following user"
  tasks: 
    - 
      win_domain_user: 
        firstname: denemefirstname
        name: deneme
        password: {{ password }}
        state: present
        surname: denemesurname
      name: "Checks a user is created, and if it is not it will create the following user"
