---
- name: check package is installed
  hosts: all
  tasks:   
    - shell: rpm -q "{{ package_name }}"
      ignore_errors: True
      register : result
    
    - command: echo "The package is existing on the system"
      when: result is succeeded
      
    - command: echo "The package is not existing on the system"
      when: result is failed
       
