---
- name: Install new package
  hosts: localhost
  connection: local
  tasks:   
  - name: Add the Linux VM to inventory as a temporary host
    add_host:          
     #Ansible
     name: "{{ ip_address }}"
     #Ansible
     ansible_user:  "{{ username }}"
     #Ansible
     ansible_password:  "{{ password }}"
     #Ansible
     ansible_ssh_port: "{{ ssh_port }}"
    
  - name: Install the latest version of Apache
    yum:
      name: httpd
      state: latest
    delegate_to: "{{ ip_address }}"
  
